//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToccWeb.wcfDou6 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfDou6.IBusinessLogic")]
    public interface IBusinessLogic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/GetDataSet", ReplyAction="http://tempuri.org/IBusinessLogic/GetDataSetResponse")]
        System.Data.DataSet GetDataSet(string FunctionCode, string var1, string var2, string var3, string var4, string var5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/UpdateSummaryRequestNo", ReplyAction="http://tempuri.org/IBusinessLogic/UpdateSummaryRequestNoResponse")]
        string UpdateSummaryRequestNo(System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/GetRequestNoBCST", ReplyAction="http://tempuri.org/IBusinessLogic/GetRequestNoBCSTResponse")]
        bool GetRequestNoBCST(string sRequestNo, int iLayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/XMLOutCom", ReplyAction="http://tempuri.org/IBusinessLogic/XMLOutComResponse")]
        System.Data.DataTable XMLOutCom(string rptStatus, string div, string rptGroup, string wkno, string sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/GetCloudTravelHistoryByID", ReplyAction="http://tempuri.org/IBusinessLogic/GetCloudTravelHistoryByIDResponse")]
        System.Data.DataTable GetCloudTravelHistoryByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLogic/GetPatientData", ReplyAction="http://tempuri.org/IBusinessLogic/GetPatientDataResponse")]
        System.Data.DataTable GetPatientData(string idNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessLogicChannel : ToccWeb.wcfDou6.IBusinessLogic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessLogicClient : System.ServiceModel.ClientBase<ToccWeb.wcfDou6.IBusinessLogic>, ToccWeb.wcfDou6.IBusinessLogic {
        
        public BusinessLogicClient() {
        }
        
        public BusinessLogicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessLogicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessLogicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessLogicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataSet(string FunctionCode, string var1, string var2, string var3, string var4, string var5) {
            return base.Channel.GetDataSet(FunctionCode, var1, var2, var3, var4, var5);
        }
        
        public string UpdateSummaryRequestNo(System.Data.DataSet ds) {
            return base.Channel.UpdateSummaryRequestNo(ds);
        }
        
        public bool GetRequestNoBCST(string sRequestNo, int iLayer) {
            return base.Channel.GetRequestNoBCST(sRequestNo, iLayer);
        }
        
        public System.Data.DataTable XMLOutCom(string rptStatus, string div, string rptGroup, string wkno, string sid) {
            return base.Channel.XMLOutCom(rptStatus, div, rptGroup, wkno, sid);
        }
        
        public System.Data.DataTable GetCloudTravelHistoryByID(string id) {
            return base.Channel.GetCloudTravelHistoryByID(id);
        }
        
        public System.Data.DataTable GetPatientData(string idNo) {
            return base.Channel.GetPatientData(idNo);
        }
    }
}
